#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xC1B74D5998A5F657 (jens@plyp.com)
#
Name     : pypi-zope.schema
Version  : 6.2.1
Release  : 64
URL      : https://files.pythonhosted.org/packages/2a/b9/84e4e7fd38adaa98c8f2fa6b783c35437fff41705d071cb6a35637f6b27b/zope.schema-6.2.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/2a/b9/84e4e7fd38adaa98c8f2fa6b783c35437fff41705d071cb6a35637f6b27b/zope.schema-6.2.1.tar.gz
Source1  : https://files.pythonhosted.org/packages/2a/b9/84e4e7fd38adaa98c8f2fa6b783c35437fff41705d071cb6a35637f6b27b/zope.schema-6.2.1.tar.gz.asc
Summary  : zope.interface extension for defining data schemas
Group    : Development/Tools
License  : ZPL-2.1
Requires: pypi-zope.schema-license = %{version}-%{release}
Requires: pypi-zope.schema-python = %{version}-%{release}
Requires: pypi-zope.schema-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(py)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(zope.event)
BuildRequires : pypi(zope.interface)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv

%description
=============
zope.schema
=============
.. image:: https://img.shields.io/pypi/v/zope.schema.svg
:target: https://pypi.org/project/zope.schema/
:alt: Latest Version

%package license
Summary: license components for the pypi-zope.schema package.
Group: Default

%description license
license components for the pypi-zope.schema package.


%package python
Summary: python components for the pypi-zope.schema package.
Group: Default
Requires: pypi-zope.schema-python3 = %{version}-%{release}

%description python
python components for the pypi-zope.schema package.


%package python3
Summary: python3 components for the pypi-zope.schema package.
Group: Default
Requires: python3-core
Provides: pypi(zope.schema)
Requires: pypi(setuptools)
Requires: pypi(zope.event)
Requires: pypi(zope.interface)

%description python3
python3 components for the pypi-zope.schema package.


%prep
%setup -q -n zope.schema-6.2.1
cd %{_builddir}/zope.schema-6.2.1
pushd ..
cp -a zope.schema-6.2.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1663257372
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-zope.schema
cp %{_builddir}/zope.schema-%{version}/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-zope.schema/a0b53f43aab58b46bf79ba756c50771c605ab4c5 || :
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-zope.schema/a0b53f43aab58b46bf79ba756c50771c605ab4c5

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
