#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : zope.schema
Version  : 4.9.1
Release  : 24
URL      : https://files.pythonhosted.org/packages/7e/8f/789374a560e8ea5e2c94e06fa755baeb2c370a1e9eaf2cd4a4667561d8a7/zope.schema-4.9.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/7e/8f/789374a560e8ea5e2c94e06fa755baeb2c370a1e9eaf2cd4a4667561d8a7/zope.schema-4.9.1.tar.gz
Summary  : zope.interface extension for defining data schemas
Group    : Development/Tools
License  : ZPL-2.1
Requires: zope.schema-python3
Requires: zope.schema-license
Requires: zope.schema-python
Requires: Sphinx
Requires: setuptools
Requires: zope.event
Requires: zope.interface
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : tox
BuildRequires : virtualenv

%description
zope.schema
        =============

%package license
Summary: license components for the zope.schema package.
Group: Default

%description license
license components for the zope.schema package.


%package python
Summary: python components for the zope.schema package.
Group: Default
Requires: zope.schema-python3 = %{version}-%{release}

%description python
python components for the zope.schema package.


%package python3
Summary: python3 components for the zope.schema package.
Group: Default
Requires: python3-core

%description python3
python3 components for the zope.schema package.


%prep
%setup -q -n zope.schema-4.9.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1538748169
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/zope.schema
cp LICENSE.txt %{buildroot}/usr/share/doc/zope.schema/LICENSE.txt
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/doc/zope.schema/LICENSE.txt

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
